name: webwidgets
description: Web Widgets library for building HTML elements using reactive Widgets.
version: 0.1.0
author: Renato Athaydes <renato@athaydes.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  build_test: any
  webdriver: any
