name: flattery
description: Flattery is a library for building HTML elements using Widgets.
version: 0.3.0
homepage: https://github.com/renatoathaydes/flattery
repository: https://github.com/renatoathaydes/flattery
issue_tracker: https://github.com/renatoathaydes/flattery/issues
author: Renato Athaydes <renato@athaydes.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.0.0
  build_runner: ^1.6.7
  build_web_compilers: ^2.2.3
  build_test: ^0.10.8
  webdriver: ^2.1.1
